# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 09:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('ND', 'Not specified')], default='ND', max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=64)),
                ('mobile_phone', models.CharField(max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='upload/avatar/')),
                ('member_since', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField()),
                ('radius', models.PositiveSmallIntegerField(default=5)),
                ('hiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_type', models.CharField(choices=[('W', 'Walk'), ('C', 'Climbing'), ('S', 'Ski')], default='W', max_length=16)),
                ('title', models.CharField(default='My hike of %d/%m/%Y', max_length=64)),
                ('mate_min', models.PositiveSmallIntegerField(default=1)),
                ('mate_max', models.PositiveSmallIntegerField(default=1)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('hike_date', models.DateField()),
                ('hike_date_margin', models.PositiveSmallIntegerField(default=0)),
                ('enrolled_hikers', models.ManyToManyField(through='findamate.Enrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('point_type', models.CharField(choices=[('S', 'Start'), ('W', 'Waypoint'), ('B', 'Base camp'), ('F', 'Finish')], default='W', max_length=16)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findamate.Hike')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='hike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findamate.Hike'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='hiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
