# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findamate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='hike_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='hike',
            old_name='hike_date_margin',
            new_name='date_margin',
        ),
        migrations.RenameField(
            model_name='hike',
            old_name='hike_type',
            new_name='type',
        ),
    ]
