# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findamate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
